version: '3.9'
services:

  user_service:
    container_name: user_service
    environment:
      - DATABASE_USER=postgres
      - DATABASE_HOST=postgresdb
      - DATABASE_NAME=homework1
      - DATABASE_PASSWORD=1234
      - DATABASE_PORT=5432
      - JWT_SECRET=secret
    build:
      context: .
      dockerfile: docker/user/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - homework1

  postgresdb:
    image: postgres:16.2-alpine3.19
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=homework1
    ports:
      - 5432:5432
    networks:
      - homework1

volumes:
  pg_data:

# Networks to be created to facilitate communication between containers
networks:
  homework1:
    driver: bridge